import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.scss";
import { Header } from "@/components/header";
import { Sidebar } from "@/components/sidebar";
import { ProjectsProvider } from "@/contexts/projects";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <>
          <ProjectsProvider>
            <Header />
            <main>
              <Sidebar />
              <div className="mainContents">{children}</div>
            </main>
          </ProjectsProvider>
        </>
      </body>
    </html>
  );
}
